import re
import traceback
from deoplete.source.base import Base

# ------------------------------- KEYWORD -------------------------------------------------------------------------
ruby_stdlib_keywords = [
    '_PermaLink?', '__drbref', '__drburi', '__evaluate__', '__exit__', '__getobj__', '__raise__', '__setobj__',
    '_dump', '_getproperty', '_gets_noecho', '_httpdate', '_invoke', '_iso', '_jisx', '_load', '_parse', '_racc_do_parse_rb',
    '_racc_do_reduce', '_racc_evalact', '_racc_init_sysvars', '_racc_setup', '_racc_yyparse_rb',
    '_rfc', '_segments', '_set_last_value', '_setproperty', '_split_segments', '_strptime', '_tilde_requirements',
    '_version', '_xmlschema', 'a', 'abbrev', 'abbreviate', 'abort', 'abs', 'absolute', 'absolute?', 'ac_arg_disable',
    'ac_arg_enable', 'ac_arg_with', 'accept', 'accept_blank_line', 'accept_block_quote', 'accept_charset',
    'accept_document', 'accept_heading', 'accept_indented_paragraph', 'accept_list_end', 'accept_list_item_end',
    'accept_list_item_start', 'accept_list_start', 'accept_loop', 'accept_nonblock', 'accept_paragraph',
    'accept_raw', 'accept_rule', 'accept_uri_http', 'accept_verbatim', 'access_log', 'acct', 'acos',
    'acosh', 'action_name', 'activate', 'activate_dependencies', 'activated', 'activated?', 'active?',
    'active_job?', 'active_jobs', 'active_jobs_exist?', 'active_process_controllers', 'add', 'add!',
    'add?', 'add_GIT', 'add_alias', 'add_also_in', 'add_always_install', 'add_attribute', 'add_attributes',
    'add_authenticator', 'add_bindir', 'add_bulk_threshold_option', 'add_c_enclosure', 'add_c_variables',
    'add_cert', 'add_certid', 'add_certificate', 'add_checksums', 'add_child_vertex', 'add_class',
    'add_class_or_module', 'add_clear_sources_option', 'add_comment', 'add_common_option', 'add_constant',
    'add_converter', 'add_crl', 'add_data', 'add_date', 'add_dependency', 'add_development_dependency',
    'add_dictionary', 'add_edge', 'add_edge_no_circular', 'add_element', 'add_entry', 'add_event',
    'add_event_to_arry', 'add_extend', 'add_extends', 'add_extension', 'add_extension_modules',
    'add_extra_args', 'add_field', 'add_file', 'add_file_digest', 'add_file_signed', 'add_file_simple',
    'add_filter', 'add_footnote', 'add_from', 'add_generator', 'add_handler', 'add_have_children_element',
    'add_html', 'add_include', 'add_includes', 'add_install_update_options', 'add_key_option',
    'add_label', 'add_line_numbers', 'add_listener', 'add_local', 'add_local_remote_options', 'add_maker',
    'add_method', 'add_method_documentation', 'add_method_list', 'add_module', 'add_module_alias',
    'add_module_by_normal_module', 'add_namespace', 'add_need_initialize_variable', 'add_nonce',
    'add_observer', 'add_option', 'add_other_element', 'add_otp_option', 'add_owners', 'add_paragraph',
    'add_path', 'add_platform', 'add_platform_option', 'add_plural_form', 'add_prerelease_option',
    'add_protocol', 'add_proxy_option', 'add_recipient', 'add_regexp_handling', 'add_regexp_handling_RDOCLINK',
    'add_regexp_handling_TIDYLINK', 'add_require', 'add_response_handler', 'add_revoked', 'add_row',
    'add_runtime_dependency', 'add_schedule', 'add_section', 'add_security_option', 'add_self_to_load_path',
    'add_signer', 'add_source_gem', 'add_source_option', 'add_spec', 'add_specific_extra_args',
    'add_specs', 'add_status', 'add_symlink', 'add_tag', 'add_text', 'add_text_tests', 'add_to', 'add_to_classes_or_modules',
    'add_to_element_method', 'add_to_fetcher', 'add_token', 'add_token_listener', 'add_tokens',
    'add_update_sources_option', 'add_value', 'add_version_option', 'add_vertex', 'add_visitor_tests',
    'add_word_pair', 'addr', 'adjugate', 'adler', 'afamily', 'after_resolution', 'ajd', 'alert', 'alert_error',
    'alert_warning', 'alias', 'alias?', 'alias_command', 'alias_extension', 'alias_map', 'alien', 'alive?',
    'all', 'all_classes', 'all_classes_and_modules', 'all_files', 'all_modules', 'all_names', 'all_spec_names',
    'all_specs', 'all_waits', 'allocation_class_path', 'allocation_generation', 'allocation_method_id',
    'allocation_sourcefile', 'allocation_sourceline', 'allow_addr?', 'allow_missing?', 'allow_nan?',
    'allow_socket?', 'alphanumeric', 'alpn_protocol', 'alt_name_or_x', 'alternate', 'amjd', 'ancestor?',
    'ancestors', 'ancestors_of', 'angle_with', 'annotate', 'antisymmetric?', 'any_content', 'api_key',
    'api_keys', 'apop?', 'app_script_text', 'append', 'append_data', 'append_features', 'appendable?',
    'approximate_recommendation', 'aref', 'aref_prefix', 'aref_to', 'arglists', 'arguments', 'array',
    'array_attributes', 'array_nl', 'as_href', 'as_json', 'as_string', 'ascend', 'ascii_only?', 'asctime',
    'asin', 'asinh', 'ask', 'ask_for_password', 'ask_if_ok', 'ask_yes_no', 'asn', 'assemble_template', 'assert_activate',
    'assert_contains_make_command', 'assert_headers_equal', 'assert_path_exists', 'asset', 'assign_names',
    'at', 'atan', 'atanh', 'atime', 'atom_validate', 'attlistdecl', 'attlistdecl?', 'attribute', 'attribute_names',
    'attribute_of', 'attributes', 'attributes_of', 'auth_cram_md', 'auth_data', 'auth_login', 'auth_only',
    'auth_plain', 'auth_tag', 'auth_tag_len', 'authenticate', 'authenticated?', 'author', 'authors',
    'avail_in', 'avail_out', 'available_specs', 'available_tags', 'axe', 'backtrace', 'backtracking!',
    'banner', 'base', 'base_dir', 'base_name', 'basename', 'basic', 'basic_auth', 'basic_quote_characters',
    'basic_word_break_characters', 'basis', 'beep', 'before_resolution', 'before_running_rdoc',
    'begin_adding', 'beginning_of_line?', 'begins?', 'benchmark', 'bin_dir', 'bin_file', 'bin_path',
    'binary', 'binary?', 'binary_mode', 'bind', 'bind_function', 'bindir', 'binmode', 'binmode?', 'binread',
    'binwrite', 'birthtime', 'bit_set?', 'bitmap_for', 'blinding_off!', 'blinding_on!', 'block_length',
    'block_output_synchronize', 'block_params', 'block_scanf', 'block_size', 'blockdev?', 'blockquote',
    'bm', 'bmbm', 'body', 'body_exist?', 'body_permitted?', 'body_reader', 'body_stream', 'bool', 'boolean',
    'both?', 'bottom', 'break_on_newline', 'break_outmost_groups', 'break_points', 'breakable', 'broadaddr',
    'broadcast', 'bubblebabble', 'buffer_initial_length', 'build', 'build_args', 'build_extensions',
    'build_heading', 'build_index', 'build_indices', 'build_info_dir', 'build_info_file', 'build_list',
    'build_marshal_gemspecs', 'build_modern_index', 'build_modern_indices', 'build_paragraph',
    'build_rake_in', 'build_verbatim', 'builtin_curves', 'bump', 'bundler_version', 'bundler_version_with_reason',
    'by_col', 'by_col!', 'by_col_or_row', 'by_col_or_row!', 'by_id', 'by_row', 'by_row!', 'byte', 'bytes',
    'bytes_read', 'c_str', 'cache_dir', 'cache_file', 'cache_path', 'cache_update_path', 'cachesize',
    'calc_checksum', 'calculate', 'call', 'call_seq', 'can_parse', 'can_parse_by_name', 'cancel', 'canceled?',
    'candidate', 'canonical', 'canonical_each', 'canonical_segments', 'canonname', 'capabilities',
    'capability', 'capable_auth_types', 'capable_cram_md', 'capable_login_auth?', 'capable_plain_auth?',
    'capable_starttls?', 'caption', 'capture', 'captures', 'cat', 'catch', 'cbrt', 'cd', 'cdata', 'cdata?', 'cdatas',
    'ceil', 'ceiling', 'cert', 'cert_files', 'cert_path', 'cert_status', 'certid', 'certificates', 'certificates_matching',
    'certs', 'chain', 'challenge', 'change_attribute', 'change_encoding', 'change_workspace', 'changed',
    'changed?', 'changed_attribute_by_name', 'char_pos', 'character', 'characters', 'chardev?', 'charpos',
    'chars', 'charset', 'chdir', 'check', 'check_arity', 'check_cert', 'check_chain', 'check_circular?',
    'check_closed', 'check_credentials_permissions', 'check_data', 'check_files', 'check_func',
    'check_func_or_macro', 'check_gems', 'check_generator', 'check_insecure_method', 'check_key',
    'check_modeline', 'check_names', 'check_nonce', 'check_password', 'check_private_key', 'check_root',
    'check_ruby_version', 'check_signedness', 'check_sizeof', 'check_trust', 'check_until', 'check_user',
    'check_userinfo', 'check_validity', 'checkbox', 'checkbox_group', 'child_name', 'children', 'chmod',
    'chmod_R', 'choose_from_list', 'chown', 'chown_R', 'chunked', 'chunked?', 'cipher', 'ciphers', 'civil',
    'class_attributes', 'class_dir', 'class_document', 'class_file', 'class_method_list', 'class_methods',
    'class_name', 'class_path', 'classes', 'classes_and_includes_and_extends_for', 'classes_and_modules',
    'classes_hash', 'classify', 'clean_gems', 'clean_text', 'cleanpath', 'cleanup', 'clear', 'clear_bit!',
    'clear_comment', 'clear_default_specs', 'clear_paths', 'client_ca', 'client_error?', 'clobber_task_description',
    'clone', 'close', 'close!', 'close_all', 'close_enabled?', 'close_read', 'close_write', 'closed?', 'closed_read?',
    'closed_write?', 'cmds', 'cmp', 'cmp_issuer', 'cmsg_is?', 'code', 'code_around_binding', 'codepage',
    'codepoints', 'coerce', 'cofactor', 'cofactor_expansion', 'col_sep', 'collect', 'collect!', 'collect_first_comment',
    'collect_tokens', 'column', 'column_separator', 'column_vector', 'column_vectors', 'columns',
    'combine', 'command', 'command_names', 'comment', 'comment?', 'comments', 'commercial', 'commit', 'common_installer_setup',
    'common_installer_teardown', 'common_options', 'compact_specs', 'compare_by_identity', 'compare_by_identity?',
    'compare_file', 'compare_language', 'compare_stream', 'compatible?', 'complain', 'complete', 'completer_quote_characters',
    'completer_word_break_characters', 'completion_append_character', 'completion_case_fold',
    'completion_proc', 'completion_quote_character', 'component', 'component_ary', 'compose_sets',
    'compress', 'compress_indices', 'compute_key', 'concat', 'conf', 'config', 'config_file', 'config_file_name',
    'configuration', 'configure', 'configure_connection_for_https', 'conflicting_dependencies',
    'conflicts', 'confstr', 'conj', 'conjugate', 'connect', 'connect_address', 'connect_from', 'connect_internal',
    'connect_nonblock', 'connect_to', 'connection_close?', 'connection_for', 'connection_keep_alive?',
    'consider_local?', 'consider_remote?', 'console', 'console_size', 'const_load', 'const_missing',
    'construct', 'consume', 'contains', 'contains_requirable_file?', 'content', 'content_encoding',
    'content_length', 'content_range', 'content_setup', 'content_type', 'contents', 'context', 'continue?',
    'continue_entry_body', 'continue_timeout', 'convert', 'convert_attrs', 'convert_flow', 'convert_html',
    'convert_regexp_handling', 'convert_regexp_handlings', 'convert_string', 'converter', 'converters',
    'convertible_int', 'cooked', 'cooked!', 'copy', 'copy_entry', 'copy_file', 'copy_nonce', 'copy_static',
    'copy_stream', 'copy_string', 'copy_to', 'correct?', 'correct_for_windows_path', 'cos', 'cosh', 'count',
    'count_imemo_objects', 'count_nodes', 'count_objects_size', 'count_observers', 'count_symbols',
    'count_tdata_objects', 'covector', 'coverage_level', 'cp', 'cp_lr', 'cp_r', 'cram_md', 'crc', 'crc_table',
    'creatable?', 'create', 'create_cert', 'create_cert_email', 'create_cert_self_signed', 'create_document',
    'create_entries', 'create_ext', 'create_ext_from_array', 'create_ext_from_hash', 'create_ext_from_string',
    'create_extension', 'create_from', 'create_guid', 'create_header', 'create_items', 'create_key',
    'create_listeners', 'create_makefile', 'create_request', 'create_response', 'create_self_signed_cert',
    'create_ssl_params', 'create_tmpdir', 'create_value', 'created_specs', 'credentials_path',
    'critical', 'critical?', 'crl', 'crls', 'cross', 'cross_product', 'cross_reference', 'css', 'ctime', 'ctrl_cmd',
    'current', 'current_cert', 'current_crl', 'current_group', 'current_line', 'current_section',
    'current_server', 'cursor', 'curve_name', 'cvs_url', 'cwday', 'cweek', 'cwyear', 'd', 'data', 'data_type',
    'datadir', 'date', 'datetime_format', 'day', 'day_fraction', 'dclone', 'deafen', 'debug', 'debug?', 'debug_level',
    'debug_msg', 'debug_output', 'debug_thread_info', 'declare', 'decode', 'decode_all', 'decode_utf',
    'decode_www_form', 'decode_www_form_component', 'decrypt', 'deduplicate_call_seq', 'deep_clone',
    'def_array_element', 'def_atom_persons', 'def_atom_text_construct', 'def_class', 'def_class_accessor',
    'def_classed_element', 'def_classed_element_without_accessor', 'def_classed_elements',
    'def_convert', 'def_corresponded_attr_reader', 'def_corresponded_attr_writer', 'def_csv_accessor',
    'def_csv_element', 'def_delegator', 'def_delegators', 'def_e', 'def_element_class_accessor',
    'def_elements_class_accessor', 'def_else_enc', 'def_erb_method', 'def_exception', 'def_explicit_clean_other_accessor',
    'def_extend_command', 'def_head_option', 'def_iconv_convert', 'def_inspector', 'def_instance_delegator',
    'def_instance_delegators', 'def_intern', 'def_method', 'def_module', 'def_name_to_int', 'def_notifier',
    'def_option', 'def_other_element', 'def_other_element_without_accessor', 'def_post_proc',
    'def_pre_proc', 'def_same_enc', 'def_single_delegator', 'def_single_delegators', 'def_system_command',
    'def_tail_option', 'def_to_euc_jp_from_iso_', 'def_to_euc_jp_from_shift_jis', 'def_to_euc_jp_from_utf_',
    'def_to_iso_', 'def_to_shift_jis_from_euc_jp', 'def_to_shift_jis_from_utf_', 'def_to_utf_',
    'def_uconv_convert_if_can', 'def_yes_other_accessor', 'default', 'default_acl', 'default_argc_limit',
    'default_bindir', 'default_cert_path', 'default_console_size', 'default_dir', 'default_event_sources',
    'default_exec_format', 'default_ext_dir_for', 'default_gem?', 'default_gems_use_full_paths?',
    'default_id_conv', 'default_imap_port', 'default_imaps_port', 'default_key_path', 'default_load_limit',
    'default_ole_types', 'default_options', 'default_parser', 'default_passive', 'default_path',
    'default_pop', 'default_port', 'default_record_separator', 'default_rubygems_dirs', 'default_safe_level',
    'default_sources', 'default_spec_cache_dir', 'default_spec_file', 'default_specifications_dir',
    'default_src_encoding', 'default_ssl_context', 'default_ssl_port', 'default_submission_port',
    'default_system_path', 'default_title', 'default_tls_port', 'default_value', 'defaults', 'defaults_str',
    'define', 'define_aliases', 'define_by_keywords', 'define_head', 'define_tail', 'defined_in?',
    'definition', 'definition_lists', 'deflate', 'degree', 'delegate', 'deletable?', 'delete', 'delete!',
    'delete?', 'delete_all', 'delete_at', 'delete_attribute', 'delete_edge', 'delete_element', 'delete_field',
    'delete_if', 'delete_legacy_args', 'delete_namespace', 'delete_observer', 'delete_observers',
    'delete_passwd', 'delete_suffix', 'delete_text', 'delete_unless_alive', 'deleted?', 'depend_rules',
    'dependencies', 'dependencies_for', 'dependency', 'dependency_order', 'dependent_gems', 'dependent_specs',
    'deprecate', 'deprecated_warning_flag', 'depth', 'dequote', 'descend', 'descendent?', 'description',
    'det', 'det_e', 'detach_vertex_named', 'detached', 'detached?', 'detect', 'detect_encoding', 'detect_gemdeps',
    'determinant', 'determinant_e', 'development?', 'development_dependencies', 'dfdxi', 'dh_compute_key',
    'diagonal', 'diagonal?', 'difference', 'dig', 'digest', 'digest!', 'digest_conf', 'digest_length', 'dir',
    'dir_config', 'direct_ancestors', 'directory?', 'directory_makable?', 'dirname', 'dirs', 'disable_close',
    'disable_ssl', 'disable_starttls', 'disable_tls', 'disconnect', 'disconnected?', 'disjoint?',
    'dispid', 'display', 'display?', 'display_attributes', 'display_class', 'display_method', 'display_name',
    'display_names', 'display_page', 'display_page_list', 'div', 'divide', 'divmod', 'dlload', 'dlopen',
    'dlunwrap', 'dlwrap', 'dn', 'do_GET', 'do_HEAD', 'do_OPTIONS', 'do_POST', 'do_aliases', 'do_attrs', 'do_boot_defclass',
    'do_classes', 'do_constants', 'do_define_class', 'do_define_class_under', 'do_define_module',
    'do_define_module_under', 'do_includes', 'do_methods', 'do_missing', 'do_modules', 'do_not_reverse_lookup',
    'do_nothing', 'do_parse', 'do_reply', 'do_singleton_class', 'do_struct_define_without_accessor',
    'do_validate', 'do_write', 'doc_dir', 'doc_root', 'doc_stats', 'doctor', 'doctype', 'doctype?', 'doctype_end',
    'document', 'document?', 'document_children', 'document_self', 'document_self_or_methods',
    'documentation_page', 'documentation_search', 'documentation_source', 'documented?', 'done',
    'done?', 'done_adding', 'done_documenting', 'done_installing', 'dot', 'double_fig', 'down', 'download',
    'download_reporter', 'download_to_cache', 'downto', 'dowrite', 'dsa_sign_asn', 'dsa_verify_asn',
    'dstaddr', 'dummy_makefile', 'dump', 'dump_all', 'dump_stream', 'dup', 'e', 'each', 'each_active_object',
    'each_address', 'each_ancestor', 'each_attribute', 'each_byte', 'each_capitalized', 'each_capitalized_name',
    'each_certificate', 'each_char', 'each_child', 'each_classmodule', 'each_codepoint', 'each_const',
    'each_constant', 'each_data', 'each_element', 'each_element_with_attribute', 'each_element_with_text',
    'each_entry', 'each_extend', 'each_filename', 'each_header', 'each_include', 'each_index', 'each_key',
    'each_line', 'each_mail', 'each_method', 'each_name', 'each_name_of', 'each_names_with_len', 'each_option',
    'each_pair', 'each_parent', 'each_prime', 'each_recursive', 'each_resource', 'each_section', 'each_source',
    'each_spec', 'each_strongly_connected_component', 'each_strongly_connected_component_from',
    'each_value', 'each_with_index', 'ecdh_curves', 'echo', 'echo?', 'egd', 'egd_bytes', 'ehlo', 'eigen', 'eigensystem',
    'eigenvalue_matrix', 'eigenvalues', 'eigenvector_matrix', 'eigenvector_matrix_inv', 'eigenvectors',
    'element', 'element_initialize_arguments?', 'elementdecl', 'elementdecl?', 'elements', 'elements_to_f',
    'elements_to_i', 'elements_to_r', 'emacs_editing_mode', 'emacs_editing_mode?', 'email_to_name',
    'emphasis', 'empty', 'empty?', 'enable_close', 'enable_config', 'enable_fallback_scsv', 'enable_shared',
    'enable_ssl', 'enable_starttls', 'enable_starttls_auto', 'enable_tls', 'enc_key', 'encode', 'encode!',
    'encode_fallback', 'encode_utf', 'encode_www_form', 'encode_www_form_component', 'encoding',
    'encrypt', 'end', 'end?', 'endElement', 'end_accepting', 'end_document', 'end_element', 'end_element?',
    'end_mapping', 'end_prefix_mapping', 'end_sequence', 'end_stream', 'ended?', 'endgrent', 'endpwent',
    'engines', 'england', 'ensure_default_gem_subdirectories', 'ensure_dependency', 'ensure_gem_subdirectories',
    'ensure_loadable_spec', 'ensure_mod_sequence_value', 'ensure_number', 'ensure_nz_number',
    'ensure_xml_content', 'enterable?', 'entity', 'entity?', 'entity_class', 'entity_expansion_limit',
    'entity_expansion_text_limit', 'entitydecl', 'entitydecl?', 'entries', 'entrywise_product',
    'env_requirement', 'environment', 'eof', 'eof?', 'eos?', 'eql?', 'error', 'error?', 'error_depth', 'error_message',
    'error_string', 'errors', 'escape', 'escapeElement', 'escapeHTML', 'escape_element', 'escape_form',
    'escape_html', 'escape_path', 'eval_history', 'eval_input', 'evaluate', 'event?', 'event_interface',
    'event_location', 'event_type', 'exact?', 'examine', 'exception', 'exception_class', 'exclude', 'exec_format',
    'exec_if', 'executable', 'executable?', 'executable_real?', 'executables', 'execute', 'exist?', 'exit',
    'exp', 'expand', 'expand_class', 'expand_hexstring', 'expand_name', 'expand_pair', 'expand_path',
    'expand_ref_in', 'expand_tabs', 'expand_value', 'expanded_name', 'expect', 'expected', 'expired?',
    'expires', 'explain', 'explanation', 'explicit?', 'exponent', 'export', 'expunge', 'extend_object',
    'extension', 'extension?', 'extension_dir', 'extensions', 'extensions_dir', 'extern', 'external_encoding',
    'extname', 'extra_args', 'extra_rdoc_files', 'extract', 'extract_bin', 'extract_call_seq', 'extract_comment',
    'extract_files', 'extract_messages', 'facility', 'fail', 'false', 'family', 'family_addrinfo', 'fast_generate',
    'fastmode', 'fatal', 'fatal?', 'fcntl', 'feed_info', 'fetch', 'fetch_file', 'fetch_http', 'fetch_https',
    'fetch_path', 'fetch_resource', 'fetch_s', 'fetch_server', 'fetch_size', 'fetch_spec', 'fetcher',
    'field', 'field?', 'field_row?', 'field_size_limit', 'fields', 'file', 'file?', 'file_dir', 'file_field',
    'file_input?', 'file_name', 'filename', 'filename_quote_characters', 'fileno', 'files', 'files_hash',
    'files_in', 'files_in_default_gem', 'files_in_gem', 'fill', 'fill_breakable', 'filter', 'filter!',
    'filter_backtrace', 'filter_methods', 'final', 'find', 'find_active_stub_by_path', 'find_alias_command',
    'find_alias_comment', 'find_all', 'find_all_by_full_name', 'find_all_by_name', 'find_all_template',
    'find_ancestor_local_symbol', 'find_attr_comment', 'find_attribute', 'find_attribute_named',
    'find_body', 'find_by_name', 'find_by_path', 'find_c_enclosure', 'find_class', 'find_class_comment',
    'find_class_method_named', 'find_class_named', 'find_class_named_from', 'find_class_or_module',
    'find_command', 'find_command_possibilities', 'find_const_comment', 'find_constant_named',
    'find_data', 'find_enclosing_module_named', 'find_executable', 'find_external_alias', 'find_external_alias_named',
    'find_file_named', 'find_files', 'find_first_recursive', 'find_gem', 'find_header', 'find_in_cache',
    'find_in_unresolved', 'find_in_unresolved_tree', 'find_inactive_by_path', 'find_include_file',
    'find_index', 'find_instance_method_named', 'find_latest_files', 'find_library', 'find_local_symbol',
    'find_method', 'find_method_named', 'find_methods', 'find_modifiers', 'find_module_named',
    'find_name', 'find_openssl_library', 'find_override_comment', 'find_pager_jruby', 'find_paths',
    'find_proxy', 'find_response', 'find_spec', 'find_spec_by_name_and_version', 'find_store',
    'find_symbol', 'find_symbol_module', 'find_system_command', 'find_text_page', 'find_type',
    'find_unique', 'find_unresolved_default_spec', 'finger', 'finish', 'finish_page_dir', 'finish_resolve',
    'finished?', 'finite?', 'fips_mode', 'first', 'first?', 'first_minor', 'fix', 'fix_basic_object_inheritance',
    'flags', 'flatten', 'flatten!', 'flock', 'floor', 'flow', 'flush', 'flush_left', 'flush_next_in', 'flush_next_out',
    'flush_sessions', 'fnmatch', 'fnmatch?', 'for', 'for_cache', 'for_current_gems', 'for_fd', 'for_spec',
    'for_spec?', 'force_documentation', 'force_quotes?', 'foreach', 'form', 'form_data', 'format', 'format_date',
    'format_datetime', 'format_text', 'formatted_program_filename', 'formatter', 'frac', 'fragment',
    'free', 'freeze', 'friday?', 'friendly_path', 'from', 'from_file', 'from_hash', 'from_list', 'from_module',
    'from_prime_division', 'from_specs', 'from_state', 'from_yaml', 'front', 'fsync', 'ftype', 'full_gem_path',
    'full_name', 'full_old_name', 'full_require_paths', 'full_spec', 'fully_documented?', 'fully_expanded_name',
    'function', 'gather_files', 'gcd', 'gem', 'gem_contents', 'gem_dir', 'gem_file_list', 'gem_install_dir',
    'gem_original_require', 'gem_repository?', 'gemdirs', 'gems_dir', 'gemspec', 'gen_body_table',
    'gen_const_table', 'gen_random', 'gen_relative_url', 'gen_sub_directories', 'gen_url', 'generate',
    'generate_bin_script', 'generate_bin_symlink', 'generate_class', 'generate_class_files',
    'generate_default_dirs', 'generate_event', 'generate_eventids', 'generate_file_files', 'generate_gzipped',
    'generate_index', 'generate_key', 'generate_key!', 'generate_line', 'generate_page', 'generate_prime',
    'generate_servlet_not_found', 'generate_servlet_root', 'generate_table_of_contents',
    'generate_windows_script', 'generation_hook', 'generator', 'generator_descriptions', 'generator_for',
    'get', 'get_all_gem_names', 'get_all_gem_names_and_versions', 'get_attribute', 'get_attribute_ns',
    'get_attributes', 'get_bool', 'get_byte', 'get_candidate_gems', 'get_cert_files', 'get_class_or_module',
    'get_class_specification', 'get_constant', 'get_elements', 'get_env_editor', 'get_fields',
    'get_file_and_line_from_caller', 'get_first', 'get_gems_to_cleanup', 'get_included_module_with_optional_parens',
    'get_instance', 'get_metadata', 'get_namespace', 'get_nth_prime', 'get_one_gem_name', 'get_one_optional_argument',
    'get_option', 'get_passwd', 'get_path', 'get_primary_gems', 'get_print', 'get_proxy_from_env',
    'get_response', 'get_screen_size', 'get_sorted_module_list', 'get_squashed_tk', 'get_svninfo',
    'get_symbol_or_name', 'get_text', 'get_thread', 'get_tk', 'get_tk_until', 'get_tkread', 'get_value',
    'getacl', 'getaddress', 'getaddress_orig', 'getaddresses', 'getaddrinfo', 'getbinaryfile', 'getbyte',
    'getc', 'getch', 'getdir', 'getgrent', 'getgrgid', 'getgrnam', 'gethostbyaddr', 'gethostbyname', 'gethostname',
    'getifaddrs', 'getlogin', 'getname', 'getnameinfo', 'getnames', 'getopts', 'getpass', 'getpeereid',
    'getpeername', 'getpty', 'getpwent', 'getpwnam', 'getpwuid', 'getquota', 'getquotaroot', 'getresource',
    'getresources', 'gets', 'getservbyname', 'getservbyport', 'getservername', 'getsockname', 'getsockopt',
    'getter', 'gettextfile', 'getwd', 'git', 'git_gem', 'git_source', 'github', 'glob', 'glob_files_in_dir',
    'goto', 'grammar', 'great_job', 'gregorian', 'gregorian?', 'gregorian_leap?', 'group', 'group_entries',
    'group_sub', 'grpowned?', 'guess', 'guid', 'gunzip', 'gzip', 'gzip_to', 'h', 'hadamard_product', 'handle',
    'handle_arguments', 'handle_attr', 'handle_class_module', 'handle_constants', 'handle_directive',
    'handle_exception', 'handle_ifdefs_in', 'handle_method', 'handle_options', 'handle_pipe', 'handle_rdoc_link',
    'handle_regexp_CROSSREF', 'handle_regexp_HARD_BREAK', 'handle_regexp_HYPERLINK', 'handle_regexp_RDOCLINK',
    'handle_regexp_SUPPRESSED_CROSSREF', 'handle_regexp_TIDYLINK', 'handle_singleton', 'handle_tab_width',
    'handler', 'handlers', 'handles?', 'has_attributes?', 'has_conflicts?', 'has_elements?', 'has_expires?',
    'has_key?', 'has_name?', 'has_next?', 'has_text?', 'has_value?', 'hash', 'hash_algorithm', 'hash_old',
    'have_author?', 'have_children_elements', 'have_const', 'have_content?', 'have_framework',
    'have_func', 'have_git?', 'have_header', 'have_library', 'have_macro', 'have_rdoc_', 'have_required_elements?',
    'have_required_values?', 'have_struct_member', 'have_type', 'have_var', 'have_xml_content?',
    'head', 'header', 'header?', 'header_convert', 'header_converters', 'header_row?', 'headers', 'helo',
    'help', 'helpcontext', 'helpfile', 'helpstring', 'here?', 'hermitian?', 'hex', 'hexdigest', 'hexdigest!',
    'hexencode', 'hidden', 'hierarchical?', 'history_file', 'hkdf', 'home_dir', 'home_workspace', 'host',
    'hostname', 'hour', 'href', 'hstack', 'html', 'html_escape', 'html_list_name', 'html_name', 'hton', 'http_default_port',
    'http_header', 'http_url', 'httpdate', 'httponly', 'https?', 'https_default_port', 'icon', 'iconv',
    'id', 'ident', 'identical?', 'identity', 'idle', 'idle_done', 'if_modified_since', 'ifindex', 'iflush',
    'ignore', 'ignore_unknown_element', 'ignore_whitespace_nodes', 'ignored?', 'imag', 'image', 'image_button',
    'image_size', 'imaginary', 'img', 'implemented_ole_types', 'implicit?', 'import', 'import_function',
    'import_symbol', 'import_value', 'in_files', 'in_path?', 'in_tt?', 'inactivate', 'inc', 'include?',
    'include_file', 'included', 'incompatible_argument_styles', 'indent', 'indent_text', 'indentation',
    'independent?', 'index', 'index_classes', 'index_in_parent', 'index_methods', 'index_pages', 'indicate_progress',
    'infinite?', 'infinity?', 'inflate', 'info', 'info?', 'inherited', 'inherited_array_reader', 'inherited_base',
    'inherited_hash_reader', 'inherited_reader', 'init', 'init_tags', 'initialize', 'initialize_clone',
    'initialize_copy', 'initialize_dup', 'initialize_http_header', 'initialize_methods_etc',
    'initialize_tracer', 'inject', 'inject_into_list', 'inline', 'inline_html?', 'inline_other?',
    'inline_other_base', 'inline_other_text?', 'inline_other_xml?', 'inline_text?', 'inline_xhtml?',
    'inner_product', 'input', 'input?', 'insert', 'insert_after', 'insert_before', 'insert_text', 'inspect',
    'inspect?', 'inspect_mode', 'inspect_raw', 'inspect_sockaddr', 'inspect_value', 'install', 'install_acl',
    'install_alias_method', 'install_class_name', 'install_date_element', 'install_default_bundler_gem',
    'install_default_gems', 'install_default_specs', 'install_dublin_core', 'install_executables',
    'install_extend_commands', 'install_file', 'install_from_gemdeps', 'install_gem', 'install_gem_user',
    'install_get_attribute', 'install_get_text_element', 'install_have_attribute_element',
    'install_have_child_element', 'install_have_children_element', 'install_hooks', 'install_id_conv',
    'install_image_favicon', 'install_image_item', 'install_indices', 'install_into', 'install_lib',
    'install_list', 'install_model', 'install_must_call_validator', 'install_ns', 'install_rdoc',
    'install_siginfo_handler', 'install_specs', 'install_system_commands', 'install_taxo_topic',
    'install_taxo_topics', 'install_text_element', 'install_update_defaults_str', 'installable?',
    'installable_platform?', 'installation_satisfies_dependency?', 'installed?', 'installed_docs',
    'installed_specs', 'instance', 'instance_attributes', 'instance_delegate', 'instance_method_list',
    'instance_methods', 'instruction', 'instruction?', 'instructions', 'int', 'int_from_prime_division',
    'interactive', 'internal_class_of', 'internal_encoding', 'internal_object_id', 'internal_super_of',
    'interrupt', 'intersect?', 'intersection', 'inv', 'inverse', 'invert', 'invert!', 'invkind', 'invoke',
    'invoke_kind', 'invoke_with_build_args', 'ioctl', 'ioflush', 'ip', 'ip?', 'ip_address', 'ip_address_list',
    'ip_pktinfo', 'ip_port', 'ip_unpack', 'ipv', 'irb', 'irb_abort', 'irb_at_exit', 'irb_context', 'irb_exit',
    'irb_level', 'irb_load', 'irb_require', 'isEqual', 'is_alias_for', 'is_reachable_from?', 'is_version_',
    'isatty', 'iseuc', 'isjis', 'iso', 'issjis', 'issuer', 'issuer_certificate', 'issuer_key_hash', 'issuer_name_hash',
    'issuer_of', 'isutf', 'italy', 'items', 'iteration!', 'iv', 'iv_len', 'jacobian', 'jd', 'jisx', 'jobs', 'jobs_exist?',
    'join', 'join_nowait', 'json_creatable?', 'json_create', 'julian', 'julian?', 'julian_leap?', 'kconv',
    'keep_alive?', 'keep_back', 'keep_drop', 'keep_end', 'keep_if', 'keep_only_files_and_directories',
    'keep_start', 'key', 'key?', 'key_len', 'keys', 'keys_with_inspector', 'kill', 'kill_job', 'l', 'lang', 'laplace_expansion',
    'last', 'lastBuildDate', 'last_error', 'last_modified', 'last_update', 'latest_rubygems_version',
    'latest_spec_for', 'latest_specs', 'latest_version?', 'latest_version_for', 'launch', 'lchmod',
    'lchown', 'ld', 'leap?', 'legacy_platform', 'length', 'level', 'level_notifier', 'levenshtein_distance',
    'lex', 'lib_dirs_glob', 'lib_files', 'liberal_parsing?', 'library_name', 'libyaml_version', 'license',
    'licenses', 'limit', 'line', 'line_buffer', 'line_index', 'line_stub', 'line_width', 'lineno', 'lines',
    'linger', 'link', 'link_entry', 'link_local?', 'link_to', 'list', 'list_end_for', 'list_files_in_directory',
    'list_item_from', 'list_item_start', 'list_known_classes', 'list_methods_matching', 'listable?',
    'listen', 'listener', 'ln', 'ln_s', 'ln_sf', 'load', 'load_all', 'load_api_keys', 'load_cache', 'load_certificate',
    'load_class', 'load_class_data', 'load_default_cert', 'load_default_key', 'load_defaults',
    'load_env_plugins', 'load_file', 'load_gemdeps', 'load_method', 'load_methods_matching', 'load_mime_types',
    'load_options', 'load_page', 'load_path_insert_index', 'load_plugins', 'load_private_key',
    'load_public_key', 'load_random_file', 'load_rdoc', 'load_spec', 'load_specs', 'load_stream',
    'load_variable_map', 'load_yaml', 'loaded_spec_names', 'local', 'local?', 'local_address', 'local_name',
    'local_variable_get', 'local_variable_set', 'locale', 'location', 'location_of_caller', 'lock',
    'log', 'logging', 'login', 'logo', 'logout', 'long_name', 'look_for_directives_in', 'lookup_method',
    'lookup_ring', 'lookup_ring_any', 'lookup_server', 'loopback?', 'lower_triangular?', 'ls', 'lshift!',
    'lstat', 'lsub', 'ludecomp', 'lup', 'lup_decomposition', 'lusolve', 'magnitude', 'mail', 'mailfrom', 'mails',
    'main', 'main_irb', 'main_thread', 'main_type', 'major_version', 'make', 'make_affine!', 'make_command',
    'make_compiler', 'make_destination_dirs', 'make_edge', 'make_expires', 'make_link', 'make_message',
    'make_methods', 'make_parser', 'make_passwd', 'make_regexp', 'make_socket', 'make_switch', 'make_symlink',
    'make_temp_directories', 'make_thread_list', 'make_tuple', 'make_variable_map', 'makedirs',
    'maker_target', 'makers', 'malloc', 'manage_owners', 'map', 'map!', 'map_gems_to_specs', 'mapping?',
    'mark', 'mark_version', 'markup', 'markup_code', 'marshal_dump', 'marshal_dump_old', 'marshal_load',
    'marshal_version', 'mask', 'mask!', 'mask_protected_sequences', 'match', 'match?', 'match_platform!',
    'match_platform?', 'match_to', 'match_to_consume', 'matched', 'matched?', 'matched_size', 'matches?',
    'matches_for_glob', 'matches_spec?', 'matching_specs', 'max_flag_count', 'max_nesting', 'max_retries',
    'max_version', 'mday', 'mdtm', 'measure', 'media_subtype', 'mem_check_start', 'member?', 'members',
    'memberwise', 'memsize_of', 'memsize_of_all', 'merge', 'merge!', 'merge_options', 'merged?', 'message',
    'message_loop', 'meta_vars', 'method_added', 'method_document', 'method_file', 'method_missing',
    'method_type', 'methods', 'methods_by_type', 'methods_matching', 'mime_split', 'mime_type', 'min',
    'min_version', 'minor', 'minor_version', 'minute', 'missing_extensions?', 'missing_version_message',
    'mjd', 'mkcol', 'mkdir', 'mkdir_p', 'mkdir_p_safe', 'mkpath', 'mktmpdir', 'mlsd', 'mlst', 'mod_add', 'mod_exp',
    'mod_inverse', 'mod_mul', 'mod_sqr', 'mod_sub', 'mode', 'models', 'module', 'module?', 'module_names',
    'modules', 'modules_hash', 'modulo', 'mon', 'mon_enter', 'mon_exit', 'mon_locked?', 'mon_owned?', 'mon_synchronize',
    'mon_try_enter', 'monday?', 'month', 'mount', 'mount_proc', 'mountpoint?', 'move', 'mtime', 'mu_lock',
    'mu_locked?', 'mu_pp', 'mu_synchronize', 'mu_try_lock', 'mu_unlock', 'mul', 'mult', 'multipart?', 'multipart_form',
    'must_C_version', 'must_call_validators', 'mv', 'n_bytes', 'n_jobs', 'n_mails', 'name', 'name_for',
    'name_for_explicit_dependency_source', 'name_for_locking_dependency_source', 'name_for_path',
    'name_path', 'name_prefix', 'name_regexp', 'name_tuple', 'namespace', 'namespace_context', 'namespace_uri',
    'namespaces', 'nan?', 'native', 'need_base', 'need_initialize_variables', 'need_otp?', 'need_parent?',
    'needs', 'negative?', 'nest', 'netmask', 'new', 'new!', 'new_alias_name', 'new_comment', 'new_cond', 'new_default_spec',
    'new_ntoh', 'new_offset', 'new_start', 'new_var', 'new_with', 'new_with_uri', 'new_with_value_if_need',
    'newobj', 'next', 'next_current', 'next_day', 'next_element', 'next_month', 'next_rotate_time', 'next_sibling',
    'next_sibling_node', 'next_token', 'next_update', 'next_wait', 'next_words_on_error', 'next_year',
    'nkf', 'nlsolve', 'nlst', 'nmake_found?', 'node_type', 'nodoc', 'noecho', 'non_aliases', 'non_nil_attributes',
    'nonblock', 'nonblock?', 'none?', 'nonzero?', 'noop', 'norm', 'normal?', 'normalize', 'normalize!', 'normalize_comment',
    'normalize_path', 'normalize_space', 'normalize_yaml_input', 'normalized', 'normalized_file_list',
    'not', 'not_after', 'not_before', 'not_found', 'not_set_name', 'notation', 'notationdecl', 'notationdecl?',
    'notations', 'note', 'note_for', 'notes', 'notify', 'notify?', 'notify_observers', 'now', 'nowrite', 'npn_protocol',
    'nprocessors', 'nread', 'nth_kday', 'nth_kday?', 'ntop', 'null', 'null?', 'num_bits', 'num_bytes', 'number',
    'object_class', 'object_nl', 'odd?', 'off', 'off_event', 'off_tags', 'offset', 'offset_vtbl', 'oflush',
    'oid', 'ok?', 'ok_to_remove?', 'old_enc', 'ole_activex_initialize', 'ole_classes', 'ole_free', 'ole_func_methods',
    'ole_get_methods', 'ole_instance_variable_get', 'ole_instance_variable_set', 'ole_method',
    'ole_method_help', 'ole_methods', 'ole_obj_help', 'ole_put_methods', 'ole_query_interface',
    'ole_reference_count', 'ole_respond_to?', 'ole_show_help', 'ole_type', 'ole_type_detail', 'ole_typelib',
    'ole_types', 'on', 'on_CHAR', 'on_attr_charref', 'on_attr_charref_hex', 'on_attr_entityref', 'on_attr_value',
    'on_attribute', 'on_backref', 'on_charref', 'on_charref_hex', 'on_comma', 'on_comment', 'on_const',
    'on_curve?', 'on_cvar', 'on_default', 'on_entityref', 'on_error', 'on_etag', 'on_event', 'on_event_with_outargs',
    'on_float', 'on_gvar', 'on_head', 'on_heredoc_beg', 'on_heredoc_end', 'on_ident', 'on_ignored_nl',
    'on_ignored_sp', 'on_imaginary', 'on_int', 'on_ivar', 'on_kw', 'on_lbrace', 'on_lbracket', 'on_lparen',
    'on_nl', 'on_op', 'on_period', 'on_rational', 'on_rbrace', 'on_rbracket', 'on_rparen', 'on_sp', 'on_stag',
    'on_stag_end', 'on_stag_end_empty', 'on_symbeg', 'on_tags', 'on_tail', 'on_tstring_beg', 'on_tstring_end',
    'on_xmldecl_encoding', 'on_xmldecl_end', 'on_xmldecl_standalone', 'on_xmldecl_version',
    'one?', 'ongoing_visibility', 'opaque', 'open', 'open!', 'open_editor', 'open_gem', 'open_message_stream',
    'open_server', 'open_uri_or_path', 'opendir', 'opened?', 'operating_system_defaults', 'opt_event',
    'option_list', 'optional?', 'options', 'optname', 'order', 'order!', 'ordering', 'ordinal', 'orig_initialize',
    'orig_name', 'orthogonal?', 'os_code', 'other_elements', 'others_possible?', 'out', 'out_of_line?',
    'outdated', 'outdated_and_latest_version', 'output', 'output?', 'output_encoding', 'output_flag_file',
    'output_name', 'owned?', 'p', 'pack_sockaddr_in', 'pack_sockaddr_un', 'padding', 'page', 'page_file',
    'page_name', 'paging?', 'pair', 'paragraph', 'param_list', 'param_seq', 'params', 'params_ok?', 'paranoid',
    'parent', 'parent?', 'parent_file_name', 'parent_name', 'parse', 'parse!', 'parse_alias', 'parse_args',
    'parse_attr', 'parse_attr_accessor', 'parse_call_parameters', 'parse_class', 'parse_comment',
    'parse_comment_tomdoc', 'parse_config', 'parse_constant', 'parse_constant_visibility', 'parse_ctype',
    'parse_dot_doc_file', 'parse_entries', 'parse_file', 'parse_files', 'parse_files_matching',
    'parse_form_data', 'parse_header', 'parse_helper', 'parse_int', 'parse_line', 'parse_make_command_line',
    'parse_meta_attr', 'parse_meta_method', 'parse_method', 'parse_method_dummy', 'parse_method_or_yield_parameters',
    'parse_method_parameters', 'parse_method_params_and_body', 'parse_module', 'parse_name',
    'parse_openssl', 'parse_printf_format', 'parse_query', 'parse_qvalues', 'parse_range_header',
    'parse_require', 'parse_rescue', 'parse_rfc', 'parse_set_cookie', 'parse_set_cookies', 'parse_signature',
    'parse_source', 'parse_statements', 'parse_stream', 'parse_struct_signature', 'parse_symbol_arg',
    'parse_symbol_in_arg', 'parse_time', 'parse_top_level_statements', 'parse_url', 'parse_visibility',
    'parse_yield', 'parseable?', 'parser', 'passwd', 'password', 'password_field', 'patch', 'path', 'path_ok?',
    'path_separator', 'path_to?', 'pathconf', 'paths', 'pattern', 'pbkdf', 'peek', 'peek_read', 'peek_result',
    'peek_tk', 'peek_token', 'peep', 'peer_cert', 'peer_cert_chain', 'peeraddr', 'peg_parse', 'pem_files_in',
    'pending', 'percent_doc', 'permanent_link', 'permanent_link?', 'permutation?', 'permute', 'permute!',
    'pfamily', 'pick_best!', 'pid', 'pipe?', 'pipeline', 'pipeline_r', 'pipeline_rw', 'pipeline_start',
    'pipeline_w', 'pkcs', 'pkg_config', 'plain_html', 'platform', 'platform_defaults', 'platforms', 'plural_forms',
    'point', 'point_conversion_form', 'pointer', 'pop', 'pop!', 'pop_possibility_state', 'pop_token',
    'pop_workspace', 'popd', 'popdir', 'popen', 'popup_menu', 'port', 'pos', 'position', 'possibilities', 'post',
    'post_build', 'post_connection_check', 'post_form', 'post_install', 'post_match', 'post_process',
    'post_processors', 'post_reset', 'post_uninstall', 'power', 'pp', 'ppx', 'pre_input_hook', 'pre_install',
    'pre_install_checks', 'pre_match', 'pre_reset', 'pre_uninstall', 'precs', 'predecessors', 'predicate',
    'predicate_to_string', 'prefetch', 'prefix', 'prefixes', 'prelude', 'prepend', 'prerelease', 'prerelease?',
    'prerelease_specs', 'pressed?', 'pretty', 'pretty_generate', 'pretty_name', 'pretty_new_name',
    'pretty_old_name', 'pretty_print', 'prev_day', 'prev_month', 'prev_words_on_error', 'prev_year',
    'previous', 'previous_element', 'previous_period_end', 'previous_sibling', 'previous_sibling_node',
    'primary', 'prime?', 'prime_division', 'prime_fasttest?', 'print', 'print_alias', 'print_attribute',
    'print_class', 'print_constant', 'print_file', 'print_mem_leaks', 'print_method', 'print_module',
    'print_profile', 'print_usage', 'printf', 'printn', 'private?', 'private_decrypt', 'private_encrypt',
    'private_key', 'private_key?', 'process', 'process_args', 'process_based_port', 'processingInstruction',
    'processing_instruction', 'progid', 'progids', 'program_name', 'progress', 'progress_rate', 'progress_reporter',
    'prompt_mode', 'prompting?', 'proper_subset?', 'proper_superset?', 'propfind', 'proppatch', 'protected_methods',
    'protocol', 'provide', 'proxy?', 'proxy_address', 'proxy_basic_auth', 'proxy_class?', 'proxy_from_env?',
    'proxy_pass', 'proxy_port', 'proxy_uri', 'proxy_user', 'proxyaddr', 'proxyport', 'prune', 'pseudo_bytes',
    'ptr', 'pubDate', 'public', 'public?', 'public_decrypt', 'public_encrypt', 'public_key', 'public_key?',
    'public_methods', 'pull', 'purgeable?', 'purpose', 'push', 'push_workspace', 'pushd', 'pushdir', 'put',
    'putbinaryfile', 'putc', 'puts', 'puttextfile', 'pwd', 'query', 'quick', 'quick_gem', 'quiet', 'quit', 'quo',
    'quote', 'quote_char', 'quote_character', 'quoting_detection_proc', 'r', 'racc_accept', 'racc_e_pop',
    'racc_next_state', 'racc_print_stacks', 'racc_print_states', 'racc_read_token', 'racc_reduce',
    'racc_shift', 'racc_token', 'radio_button', 'radio_group', 'raise', 'raise_for_undefined_entity?',
    'random_add', 'random_bytes', 'random_iv', 'random_key', 'random_string', 'range', 'range_length',
    'rank', 'rank_e', 'raw', 'raw!', 'raw_cookie', 'raw_path', 'rb_files_in', 'rb_scan_args', 'rcptto', 'rcptto_list',
    'rdoc', 'rdoc_installed?', 'rdoc_options', 'rdoc_task_description', 're_sign', 're_sign_cert',
    'reachable_objects_from', 'reachable_objects_from_root', 'read', 'read_all', 'read_binary',
    'read_body', 'read_cache', 'read_checksums', 'read_directive', 'read_documentation_modifiers',
    'read_file', 'read_ids', 'read_nonblock', 'read_smime', 'read_timeout', 'readable?', 'readable_after_eof?',
    'readable_real?', 'readbyte', 'readchar', 'readline', 'readlines', 'readlink', 'readpartial', 'ready',
    'ready?', 'real', 'real?', 'realdirpath', 'realloc', 'really_verbose', 'realpath', 'realtime', 'reason',
    'reason_phrase', 'receive', 'recipients', 'record_depth', 'record_entity_expansion', 'record_location',
    'record_requirements', 'recover', 'rect', 'rectangular', 'recurse_proc', 'recursive_predecessors',
    'recursive_successors', 'recv', 'recv_io', 'recv_nonblock', 'recvfrom', 'recvfrom_nonblock', 'recvmsg',
    'recvmsg_nonblock', 'redirect?', 'redirector', 'redisplay', 'ref', 'reference', 'refresh', 'refresh_line',
    'refute_path_exists', 'regenerate_binstubs', 'regexp', 'regist', 'regist_server', 'register',
    'register_command', 'register_default_spec', 'register_uri', 'registered', 'registry', 'regular?',
    'rehash', 'reject', 'reject!', 'relative?', 'relative_path_from', 'release', 'reload', 'remainder',
    'remote', 'remote?', 'remote_address', 'remote_ip', 'remove', 'remove_all', 'remove_by_name', 'remove_coding_comment',
    'remove_comment', 'remove_commented_out_lines', 'remove_dir', 'remove_entry', 'remove_entry_secure',
    'remove_executables', 'remove_file', 'remove_from_documentation?', 'remove_frozen_string_literal',
    'remove_handler', 'remove_installed!', 'remove_invisible', 'remove_magic_comment', 'remove_modeline',
    'remove_nodoc', 'remove_nodoc_children', 'remove_old_bin_files', 'remove_old_lib_files',
    'remove_option', 'remove_owners', 'remove_private', 'remove_private_comment', 'remove_response_handler',
    'remove_server', 'remove_siginfo_handler', 'remove_spec', 'remove_specs_unsatisfied_by',
    'remove_token_listener', 'remove_unparseable', 'remove_unresolved_default_spec', 'renamable?',
    'rename', 'render', 'render_template', 'renew', 'reopen', 'reorganize', 'replace', 'replace_child',
    'replace_with', 'reply', 'reply_service', 'report', 'report_attributes', 'report_class_module',
    'report_constants', 'report_methods', 'represent_map', 'represent_object', 'represent_scalar',
    'represent_seq', 'request', 'request_body_permitted?', 'request_context', 'request_get', 'request_head',
    'request_path', 'request_post', 'request_uri', 'requester', 'require', 'require_io_console', 'require_path',
    'require_paths', 'required_attribute?', 'required_attributes', 'required_prefix', 'required_ruby_version',
    'required_rubygems_version', 'required_uri', 'requirement', 'requirement!', 'requirement_satisfied_by?',
    'requirements', 'requirements_list', 'rerdoc_task_description', 'reset', 'reset_nil_attributes_to_default',
    'resolve', 'resolve_aliases', 'resolve_current', 'resources', 'respond_to?', 'respond_to_missing?',
    'response_body_permitted?', 'responses', 'rest', 'rest?', 'rest_size', 'restore', 'restsize', 'result',
    'result_with_hash', 'resume', 'retrbinary', 'retrieve_comment_body', 'retrlines', 'return_headers?',
    'return_type', 'return_type_detail', 'return_vtype', 'retval?', 'reverse', 'reverse_each', 'reverse_each_name',
    'reverse_each_name_with_prefix_optional', 'revocation_reason', 'revocation_time', 'revoked',
    'rewind', 'rewind_to', 'rfc', 'ri_dir', 'ri_installed?', 'ri_paths', 'rm', 'rm_f', 'rm_r', 'rm_rf', 'rmdir',
    'rmtree', 'root', 'root?', 'root_node', 'root_search', 'root_vertex_named', 'roots', 'round', 'route_from',
    'route_to', 'row', 'row_count', 'row_sep', 'row_separator', 'row_size', 'row_vector', 'row_vectors',
    'rows', 'rset', 'rshift!', 'rss', 'ruby', 'ruby?', 'ruby_api_version', 'ruby_engine', 'ruby_version', 'rubybin',
    'rubygems_api_key', 'rubygems_api_request', 'rubygems_target_version', 'rubygems_version',
    'run', 'run_config', 'running?', 'runtime?', 'runtime_dependencies', 's', 'safe_delete', 'safe_load',
    'safe_unlink', 'sanitize', 'sanitize_path', 'sanitize_string', 'satisfied_by?', 'satisfies_requirement?',
    'saturday?', 'save', 'save_cache', 'save_class', 'save_exception_mode', 'save_history', 'save_limit',
    'save_loaded_features', 'save_method', 'save_page', 'save_rounding_mode', 'say', 'scalar', 'scalar?',
    'scan', 'scan_all', 'scan_full', 'scan_make_command_lines', 'scan_until', 'scanf', 'scheme', 'scheme_list',
    'scope', 'scrolling_list', 'scrypt', 'search', 'search_const', 'search_for', 'search_for_dependency',
    'search_full', 'search_record', 'search_servlet', 'search_string', 'searcher', 'sec', 'sec_fraction',
    'second', 'second_fraction', 'section', 'section_contents', 'sections', 'secure', 'security_level',
    'see', 'seed', 'seek', 'select', 'select!', 'send', 'send_gem', 'send_io', 'send_mail', 'send_message', 'send_request',
    'sendcmd', 'sender', 'sendmail', 'sendmsg', 'sendmsg_nonblock', 'separator', 'seq', 'sequence', 'sequence?',
    'serial', 'server_error?', 'server_name', 'service', 'session', 'session_add', 'session_cache_mode',
    'session_cache_size', 'session_cache_stats', 'session_remove', 'session_reused?', 'set', 'set_api_key',
    'set_attributes', 'set_attrs', 'set_backtrace', 'set_bit!', 'set_close_on_exec', 'set_constant_visibility_for',
    'set_content_type', 'set_crt_params', 'set_ctypes', 'set_current_section', 'set_debug_output',
    'set_default', 'set_default_paths', 'set_dictionary', 'set_dn', 'set_encoding', 'set_eoutvar',
    'set_error', 'set_extensions', 'set_factors', 'set_filter', 'set_form', 'set_form_data', 'set_generator',
    'set_get_line_procs', 'set_headers', 'set_host', 'set_key', 'set_last_thread', 'set_last_value',
    'set_next_element', 'set_non_blocking', 'set_opaque', 'set_option', 'set_options', 'set_params',
    'set_passwd', 'set_password', 'set_path', 'set_payload', 'set_port', 'set_pqg', 'set_range', 'set_redirect',
    'set_scheme', 'set_scope', 'set_screen_size', 'set_size', 'set_socket', 'set_to', 'set_to_infinity!',
    'set_trace', 'set_typecode', 'set_user', 'set_userinfo', 'set_visibility_for', 'setacl', 'setgid?',
    'setgrent', 'setproperty', 'setpwent', 'setquota', 'setsockopt', 'setter', 'setuid?', 'setup', 'setup_certificate',
    'setup_generator', 'setup_maker', 'setup_maker_elements', 'setup_output_dir', 'setup_pager',
    'setup_params', 'setup_scanner', 'setup_signer', 'setup_ssl_context', 'sev_threshold', 'sexp',
    'sexp_raw', 'sfork', 'shallow_eql?', 'shebang', 'shellescape', 'shelljoin', 'shellsplit', 'shellwords',
    'shift', 'short_name', 'show_documentation', 'show_files', 'show_help', 'show_lookup_failure',
    'show_owners', 'show_rdoc_for_pattern', 'show_release_notes', 'show_version', 'shutdown', 'sign',
    'sign_in', 'sign_pss', 'sign_s', 'signal', 'signal_handle', 'signal_status', 'signature', 'signature_algorithm',
    'signed?', 'signed_time', 'signers', 'silent_system', 'sin', 'single?', 'single_delegate', 'singleline_format',
    'singleton_method_added', 'singular?', 'sinh', 'site', 'site_dir', 'size', 'size?', 'size_opt_params',
    'size_params', 'sizeof', 'skew_symmetric?', 'skip', 'skip_blanks?', 'skip_during', 'skip_for_variable',
    'skip_lines', 'skip_method', 'skip_optional_do_after_expression', 'skip_tkspace', 'skip_tkspace_comment',
    'skip_tkspace_without_nl', 'skip_until', 'sleep', 'slice', 'sn', 'snippet', 'sockaddr_in', 'sockaddr_un',
    'socket?', 'socketpair', 'socktype', 'solve', 'sort', 'sort_dependencies', 'sort_obj', 'sort_sections',
    'sorted', 'sorted_requests', 'source', 'source_file', 'source_for', 'source_ole_types', 'source_paths',
    'sources', 'space', 'space_before', 'spawn', 'spec', 'spec_cache_dir', 'spec_dir', 'spec_file', 'spec_for',
    'spec_for_dependency', 'spec_groups', 'spec_name', 'spec_path', 'spec_predecessors', 'special_prefixes',
    'specific?', 'specific_extra_args', 'specific_extra_args_hash', 'specs', 'specs_in', 'split',
    'split_header_value', 'split_into_flow', 'sqr', 'sqrt', 'square?', 'src_type', 'ssl?', 'ssl_params',
    'ssl_servername_callback', 'ssl_version', 'stand_alone?', 'start', 'startElement', 'start_accepting',
    'start_collecting_tokens', 'start_doc', 'start_document', 'start_element', 'start_element?',
    'start_export', 'start_import', 'start_job', 'start_mapping', 'start_prefix_mapping', 'start_profile',
    'start_sequence', 'start_server', 'start_service', 'start_stream', 'started?', 'starts_with',
    'starttls', 'starttls?', 'starttls_always?', 'starttls_auto?', 'stat', 'state', 'status', 'status?',
    'status_line', 'status_string', 'status_type_char', 'stdout', 'step', 'sticky?', 'stop', 'stop_doc',
    'stop_profile', 'stop_service', 'storbinary', 'store', 'store_for', 'storlines', 'stream', 'stream?',
    'stream_end?', 'streaming?', 'strftime', 'strict_decode', 'strict_encode', 'strict_oct', 'strike',
    'string', 'string_length', 'string_value', 'strip_hashes', 'strip_locations', 'strip_newlines',
    'strip_stars', 'strong', 'strongly_connected_components', 'strptime', 'struct', 'stubbed?', 'stubs',
    'stubs_for', 'su', 'sub', 'sub_ext', 'sub_type', 'subdomain_of?', 'subject', 'subject_certificate',
    'subject_request', 'submit', 'subscribe', 'subset?', 'substring', 'substring_after', 'substring_before',
    'subtract', 'succ', 'success?', 'successors', 'suffix_pattern', 'suffixes', 'suggest_gems_from_name',
    'suggestions', 'sum', 'summarize', 'summary', 'sunday?', 'super_each', 'superclass', 'superclass_method',
    'superset?', 'supported?', 'suppress', 'suppressed?', 'suspend', 'suspend_context', 'suspend_input_method',
    'suspend_name', 'suspend_workspace', 'switch', 'switch_name', 'sym', 'symbolize', 'symlink', 'symlink?',
    'symmetric?', 'sync', 'sync_exclusive?', 'sync_extend', 'sync_inspect', 'sync_lock', 'sync_locked?',
    'sync_point?', 'sync_shared?', 'sync_synchronize', 'sync_try_lock', 'sync_unlock', 'synchronize',
    'syncmode', 'sysaccept', 'sysclose', 'sysconf', 'sysconfdir', 'syslog', 'sysopen', 'sysread', 'syssign',
    'system', 'system_dir', 'system_path', 'systmpdir', 'sysverify', 'syswrite', 't', 'table', 'table_of_contents',
    'tag', 'tag_end', 'tag_name', 'tag_start', 'taint', 'take', 'tan', 'tanh', 'tar_dir_header', 'tar_file_header',
    'tar_symlink_header', 'tcp', 'tcp_server_loop', 'tcp_server_sockets', 'teardown', 'tee', 'tell',
    'template_dir_for', 'template_files', 'template_files_in', 'template_for', 'template_result',
    'terminate', 'terminate_interaction', 'terminate_job', 'terminated?', 'test', 'test_accept_blank_line',
    'test_accept_block_quote', 'test_accept_document', 'test_accept_heading', 'test_accept_heading_',
    'test_accept_heading_b', 'test_accept_heading_indent', 'test_accept_heading_suppressed_crossref',
    'test_accept_list_end_bullet', 'test_accept_list_end_label', 'test_accept_list_end_lalpha',
    'test_accept_list_end_note', 'test_accept_list_end_number', 'test_accept_list_end_ualpha',
    'test_accept_list_item_end_bullet', 'test_accept_list_item_end_label', 'test_accept_list_item_end_lalpha',
    'test_accept_list_item_end_note', 'test_accept_list_item_end_number', 'test_accept_list_item_end_ualpha',
    'test_accept_list_item_start_bullet', 'test_accept_list_item_start_label', 'test_accept_list_item_start_lalpha',
    'test_accept_list_item_start_note', 'test_accept_list_item_start_note_', 'test_accept_list_item_start_note_multi_description',
    'test_accept_list_item_start_note_multi_label', 'test_accept_list_item_start_number',
    'test_accept_list_item_start_ualpha', 'test_accept_list_start_bullet', 'test_accept_list_start_label',
    'test_accept_list_start_lalpha', 'test_accept_list_start_note', 'test_accept_list_start_number',
    'test_accept_list_start_ualpha', 'test_accept_paragraph', 'test_accept_paragraph_b',
    'test_accept_paragraph_br', 'test_accept_paragraph_break', 'test_accept_paragraph_i',
    'test_accept_paragraph_indent', 'test_accept_paragraph_plus', 'test_accept_paragraph_star',
    'test_accept_paragraph_underscore', 'test_accept_paragraph_wrap', 'test_accept_raw',
    'test_accept_rule', 'test_accept_rule_indent', 'test_accept_verbatim', 'test_accept_verbatim_big_indent',
    'test_accept_verbatim_indent', 'test_all', 'test_attributes', 'test_civil', 'test_commercial',
    'test_end_accepting', 'test_list_nested', 'test_list_verbatim', 'test_nth_kday', 'test_ordinal',
    'test_start_accepting', 'test_unit_conv', 'test_weeknum', 'text', 'text?', 'text_field', 'textarea',
    'textinput', 'texts', 'this', 'this_update', 'thread', 'thread_list', 'thread_list_all', 'thursday?',
    'time', 'time_delta_string', 'timeout', 'timeouts', 'timestamp', 'title', 'tk_nl?', 'tls?', 'tmp_key',
    'tmpdir', 'to', 'to_a', 'to_ary', 'to_atom', 'to_basic', 'to_bn', 'to_class_name', 'to_csv', 'to_d', 'to_date',
    'to_datetime', 'to_der', 'to_digits', 'to_dot', 'to_element_methods', 'to_f', 'to_feed', 'to_feed_for_categories',
    'to_fullpath', 'to_h', 'to_hash', 'to_html', 'to_i', 'to_id', 'to_int', 'to_io', 'to_json', 'to_json_raw',
    'to_json_raw_object', 'to_mailtext', 'to_matrix', 'to_name', 'to_obj', 'to_oct', 'to_octet_string',
    'to_path', 'to_pem', 'to_ptr', 'to_r', 'to_range', 'to_request_set', 'to_rfc', 'to_rss', 'to_ruby', 'to_ruby_for_cache',
    'to_s', 'to_set', 'to_sockaddr', 'to_spec', 'to_specs', 'to_str', 'to_string', 'to_text', 'to_time', 'to_toc',
    'to_utf', 'to_value', 'to_xml', 'to_yaml', 'today', 'toeuc', 'tojis', 'token_listener', 'token_pos', 'token_stream',
    'token_to_str', 'tokenize', 'tokens_to_s', 'tolocale', 'tomdoc?', 'top', 'top_level', 'top_level_test',
    'toplevel_load', 'tosjis', 'total_in', 'total_out', 'touch', 'toutf', 'tr', 'trace', 'trace_func', 'trace_object_allocations',
    'trace_object_allocations_clear', 'trace_object_allocations_debug_start', 'trace_object_allocations_start',
    'trace_object_allocations_stop', 'transact', 'transaction', 'transform', 'translate', 'transpose',
    'traverse', 'traverse_parents', 'tree', 'true', 'truncate', 'truncate_text', 'trust', 'trust_cert',
    'trust_dir', 'trusted_certificates', 'try_activate', 'try_const', 'try_mon_enter', 'try_type',
    'tsort', 'tsort_each', 'tsort_each_child', 'tsort_each_node', 'tt?', 'tt_sections', 'tty?', 'tuesday?',
    'type', 'type_params', 'typealias', 'typecode', 'typekind', 'typelibs', 'typename', 'u', 'ucmp', 'udp', 'udp_server_loop',
    'udp_server_loop_on', 'udp_server_recv', 'udp_server_sockets', 'ui', 'uid_copy', 'uid_fetch',
    'uid_move', 'uid_search', 'uid_sort', 'uid_store', 'uid_thread', 'uidl', 'umount', 'unadvise', 'unalias_command',
    'uname', 'unconverted_fields?', 'undef_system_command', 'undoc_params', 'unescape', 'unescapeElement',
    'unescapeHTML', 'unescape_element', 'unescape_form', 'unescape_html', 'unget', 'unget_tk', 'ungetbyte',
    'ungetc', 'uninstall', 'uninstall_all', 'uninstall_dep', 'uninstall_gem', 'uninstall_old_gemcutter',
    'uninstall_specific', 'union', 'unique_classes', 'unique_classes_and_modules', 'unique_id',
    'unique_modules', 'unit', 'unitary?', 'unix', 'unix?', 'unix_path', 'unix_rights', 'unix_server_loop',
    'unix_server_socket', 'unknown', 'unlink', 'unlock', 'unmask_protected_sequences', 'unmount',
    'unnormalize', 'unnormalized', 'unpack', 'unpack_sockaddr_in', 'unpack_sockaddr_un', 'unregist',
    'unregister_command', 'unresolved_deps', 'unresolved_names', 'unscan', 'unset_api_key!', 'unshift',
    'unsubscribe', 'untaint', 'untrust', 'unused', 'up', 'update', 'update_aliases', 'update_cache?', 'update_checksum',
    'update_extends', 'update_gem', 'update_gems', 'update_includes', 'update_index', 'update_output_dir',
    'update_parser_of_file', 'update_rubygems', 'update_specs_index', 'updated', 'upgrade_to_class',
    'upper_bound', 'upper_triangular?', 'upto', 'uptodate?', 'uri', 'uri_encode', 'uri_option', 'uri_registered?',
    'url_encode', 'urlsafe_base', 'urlsafe_decode', 'urlsafe_encode', 'usage', 'use_gemdeps', 'use_headers?',
    'use_loader', 'use_loader?', 'use_markup', 'use_paths', 'use_prefix', 'use_readline', 'use_ssl',
    'use_ssl?', 'use_tracer', 'use_ui', 'user', 'user_agent', 'user_dir', 'user_home', 'usercode', 'userinfo',
    'util_build_gem', 'util_clear_RUBY_VERSION', 'util_clear_gems', 'util_dir_entry', 'util_entry',
    'util_gem', 'util_gzip', 'util_inst_bindir', 'util_installer', 'util_make_exec', 'util_make_gems',
    'util_remove_gem', 'util_restore_RUBY_VERSION', 'util_set_RUBY_VERSION', 'util_set_arch',
    'util_setup_fake_fetcher', 'util_setup_gem', 'util_setup_spec_fetcher', 'util_spec', 'util_symlink_entry',
    'util_zip', 'utime', 'uuid', 'v', 'v_inv', 'valid?', 'valid_civil?', 'valid_commercial?', 'valid_date?',
    'valid_jd?', 'valid_mod_sequence_value?', 'valid_number?', 'valid_nz_number?', 'valid_ordinal?',
    'validate', 'validate_dependencies', 'validate_duplicate_links', 'validate_for_stream',
    'validate_metadata', 'validate_one_tag_name', 'validate_permissions', 'value', 'value?', 'values',
    'values_at', 'variable_is_set?', 'variable_kind', 'variables', 'varkind', 'vartype', 'vc_windows?',
    'ver', 'verbose', 'verbose?', 'verify', 'verify_api_key', 'verify_callback', 'verify_certificate',
    'verify_certificate_identity', 'verify_certificate_message', 'verify_entry', 'verify_files',
    'verify_gem', 'verify_gem_file', 'verify_pss', 'verify_result', 'verify_signatures', 'verify_spec',
    'version', 'version_', 'versions', 'vertex_named', 'vhid', 'vi_editing_mode', 'vi_editing_mode?',
    'virtual_host', 'visibility', 'visible?', 'visit_Array', 'visit_BasicObject', 'visit_BigDecimal',
    'visit_Class', 'visit_Complex', 'visit_Date', 'visit_DateTime', 'visit_Delegator', 'visit_Encoding',
    'visit_Enumerator', 'visit_Exception', 'visit_FalseClass', 'visit_Float', 'visit_Hash', 'visit_Integer',
    'visit_Module', 'visit_NameError', 'visit_NilClass', 'visit_Object', 'visit_Psych_Nodes_Alias',
    'visit_Psych_Nodes_Document', 'visit_Psych_Nodes_Mapping', 'visit_Psych_Nodes_Scalar',
    'visit_Psych_Nodes_Sequence', 'visit_Psych_Nodes_Stream', 'visit_Psych_Omap', 'visit_Psych_Set',
    'visit_Range', 'visit_Rational', 'visit_Regexp', 'visit_String', 'visit_Struct', 'visit_Symbol',
    'visit_Time', 'visit_TrueClass', 'voidcmd', 'vstack', 'w', 'wait', 'wait?', 'wait_all_jobs_execution',
    'wait_for_child_process_to_exit', 'wait_readable', 'wait_to_finish_all_process_controllers',
    'wait_until', 'wait_while', 'wait_writable', 'waiting', 'waiting_job?', 'waiting_jobs', 'waiting_jobs_exist?',
    'warn', 'warn?', 'wday', 'weakref_alive?', 'wednesday?', 'weeknum', 'when_invoked', 'which_to_update',
    'whitespace', 'why_not_ok?', 'win', 'win_platform', 'win_platform?', 'windows_stub_script', 'winsize',
    'with', 'with_config', 'with_index', 'with_object', 'with_response', 'wordy', 'workspaces', 'world_readable?',
    'world_writable?', 'wrap', 'writable?', 'writable_real?', 'write', 'write_binary', 'write_build_info_file',
    'write_cache_file', 'write_cdata', 'write_comment', 'write_default_spec', 'write_document',
    'write_element', 'write_file', 'write_headers?', 'write_instruction', 'write_nonblock', 'write_options',
    'write_random_file', 'write_services', 'write_smime', 'write_spec', 'write_style_sheet', 'write_text',
    'write_timeout', 'write_with_substitution', 'xhtml', 'xlist', 'xml', 'xmlDecl', 'xml_content', 'xml_decl',
    'xml_getter', 'xml_setter', 'xmldecl', 'xmldecl?', 'xmlschema', 'xmp', 'xpath', 'yaml', 'yaml_tag', 'yank_gem',
    'yday', 'year', 'yyaccept', 'yyerrok', 'yyerror', 'yyparse', 'zero', 'zero?', 'zip?', 'zlib_version', 'zone',
    'zone_offset', 'AAAA', 'AC', 'ACL', 'ACLEntry', 'ACLList', 'ANY', 'APISet', 'APISpecification', 'APOP', 'ASCIIZ',
    'Abbrev', 'Abort', 'AbstractNotifier', 'AbstractServlet', 'Acceptables', 'AccessLog', 'AccessLogError',
    'Action', 'ActivationRequest', 'AddEdgeNoCircular', 'AddressFamilyError', 'Addrinfo', 'Alias',
    'Alt', 'AmbiguousArgument', 'AmbiguousOption', 'AncillaryData', 'AnonClass', 'AnyMethod', 'AppendFile',
    'AppendIO', 'Arguable', 'Array', 'Atom', 'AtomCategory', 'AtomGenerator', 'AtomLink', 'AtomLogo', 'AtomPersonConstructBase',
    'AtomPersons', 'AtomTextConstruct', 'AtomTextConstructBase', 'AttlistDecl', 'Attr', 'AttrChanger',
    'AttrSpan', 'Attribute', 'AttributeError', 'AttributeManager', 'Attributes', 'Authenticator',
    'Author', 'AuthorBase', 'Authors', 'AuthorsBase', 'AvailableSet', 'BN', 'BNError', 'BadAlias', 'BadRequirementError',
    'BadResponseError', 'BadURIError', 'Bag', 'Base', 'BaseDublinCoreModel', 'BaseListener', 'BaseModel',
    'BaseParser', 'BaseTrackBackModel', 'BasicAuth', 'BasicLog', 'BasicResponse', 'BasicSocket', 'BasicSpecification',
    'BasicTypes', 'Benchmark', 'BestSet', 'BigDecimal', 'BigMath', 'Bignum', 'Binding', 'BlankLine', 'BlockCaller',
    'BlockParser', 'BlockQuote', 'BodyTypeAttachment', 'BodyTypeBasic', 'BodyTypeExtension', 'BodyTypeMessage',
    'BodyTypeMultipart', 'BodyTypeText', 'BoundedStream', 'BufError', 'BufferedSSLSocket', 'BufferedSocket',
    'Buffering', 'BuildCommand', 'BuildError', 'Builder', 'BuiltInCommand', 'Bundler', 'BundlerVersionFinder',
    'ByeResponseError', 'CData', 'CGI', 'CGIHandler', 'CMath', 'CNAME', 'CParser', 'CRCError', 'CRL', 'CRLError',
    'CSV', 'CStruct', 'CStructBuilder', 'CStructEntity', 'CUnion', 'CUnionEntity', 'Cat', 'Categories',
    'CategoriesBase', 'Category', 'CategoryBase', 'CertCommand', 'Certificate', 'CertificateError',
    'CertificateId', 'ChangeLog', 'ChangeWorkspace', 'Channel', 'ChannelBase', 'CheckCommand', 'Child',
    'ChildExited', 'Choice', 'ChunkedWrapper', 'Cipher', 'CipherError', 'CircularDatastructure', 'CircularDependencyError',
    'Class', 'ClassLoader', 'ClassMethods', 'ClassModule', 'CleanupCommand', 'ClientError', 'Closure',
    'Cloud', 'CloudBase', 'CmakeBuilder', 'CodeObject', 'Coder', 'Command', 'CommandLineError', 'CommandManager',
    'CommandProcessor', 'Commands', 'Comment', 'CommonModel', 'CompletingHash', 'Completion', 'Complex',
    'ComposedSet', 'CompositeHandler', 'CompositeNotifier', 'Concat', 'ConditionVariable', 'Config',
    'ConfigError', 'ConfigFile', 'ConfigureBuilder', 'Conflict', 'ConflictError', 'ConnectionPools',
    'ConsoleUI', 'Constant', 'Constants', 'Constructive', 'Content', 'ContentBase', 'ContentModel', 'ContentsCommand',
    'Context', 'ContextExtender', 'Contributor', 'ContributorBase', 'Contributors', 'ContributorsBase',
    'ConversionError', 'Converter', 'Cookie', 'Coord', 'Copy', 'Copyright', 'CopyrightBase', 'Coverage',
    'CparseParams', 'CrossReference', 'CurrentContext', 'CurrentSet', 'CurrentWorkingWorkspace',
    'Cyclic', 'DBM', 'DBMError', 'DH', 'DHError', 'DLError', 'DNS', 'DRb', 'DRbArray', 'DRbBadScheme', 'DRbBadURI',
    'DRbConn', 'DRbConnError', 'DRbError', 'DRbIdConv', 'DRbMessage', 'DRbObject', 'DRbObjectTemplate',
    'DRbObservable', 'DRbProtocol', 'DRbRemoteError', 'DRbSSLSocket', 'DRbServer', 'DRbServerNotFound',
    'DRbTCPSocket', 'DRbUNIXSocket', 'DRbUndumped', 'DRbUnknown', 'DRbUnknownError', 'DSA', 'DSAError',
    'DSL', 'DTD', 'Daemon', 'Darkfish', 'DataError', 'DataFormatError', 'Date', 'DateConstruct', 'DateTime',
    'Day', 'DayBase', 'Declaration', 'DecodeError', 'DefMethod', 'Default', 'DefaultFileHandler', 'DefaultUserInteraction',
    'Deflate', 'DelegateClass', 'Delegates', 'Delegator', 'Delete', 'DeleteEdge', 'DeleteSuffix', 'Dependency',
    'DependencyCommand', 'DependencyError', 'DependencyGraph', 'DependencyInstaller', 'DependencyList',
    'DependencyRemovalException', 'DependencyRequest', 'DependencyResolutionError', 'DependencyState',
    'Deprecate', 'DepthFirst', 'Description', 'DescriptionBase', 'DetachVertexNamed', 'Digest', 'DigestAuth',
    'DigestError', 'DigestIO', 'Dir', 'DisallowedClass', 'DocType', 'Doctor', 'Document', 'DocumentError',
    'DomainName', 'Driver', 'DryRun', 'DublinCoreModel', 'DumperOptions', 'DuplicateLinkChecker',
    'E', 'EC', 'ECError', 'ECONNABORTED', 'ECONNRESET', 'EOFError', 'EPROTO', 'ERB', 'ERBHandler', 'ERBIO', 'ERBPartial',
    'Echo', 'EigenvalueDecomposition', 'Element', 'ElementDecl', 'Elements', 'Email', 'Emitter', 'Enclosure',
    'EnclosureBase', 'EncodeError', 'Encoding', 'EndOfYAMLException', 'Engine', 'EngineError', 'English',
    'EnsureXMLContent', 'Entity', 'EntityConst', 'EntityDecl', 'Entry', 'Enumerable', 'EnvironmentCommand',
    'EratosthenesGenerator', 'EratosthenesSieve', 'Err', 'Errno', 'Error', 'ErrorReason', 'Escape', 'Etc',
    'Event', 'Exception', 'ExplicitCleanOther', 'Ext', 'ExtConfBuilder', 'ExtConfig', 'ExtServ', 'ExtServManager',
    'Extend', 'ExtendCommand', 'ExtendCommandBundle', 'Extension', 'ExtensionError', 'ExtensionFactory',
    'ExternalEntity', 'FTP', 'FTPConnectionError', 'FTPError', 'FTPPermError', 'FTPProtoError', 'FTPReplyError',
    'FTPTempError', 'Facility', 'Fail', 'FakeFetcher', 'FakePackage', 'FalseClass', 'Fcntl', 'Feed', 'FetchCommand',
    'FetchError', 'Fiddle', 'FieldsConverter', 'File', 'FileHandler', 'FileInputMethod', 'FileOverflow',
    'FilePermissionError', 'FileStore', 'FileUtils', 'Filter', 'Find', 'Fixnum', 'FlagCountError', 'Float',
    'Foreground', 'Fork', 'FormData', 'FormatError', 'FormatException', 'FormatSpecifier', 'FormatString',
    'Formatter', 'FormatterTestCase', 'Formatters', 'Forwardable', 'Frame', 'Function', 'Functions',
    'GDBM', 'GDBMError', 'GDBMFatalError', 'GW', 'GWIdConv', 'Gem', 'GemDependencyAPI', 'GemNotFoundException',
    'GemNotInHomeException', 'GemRunner', 'GemcutterUtilities', 'GenerateIndexCommand', 'Generator',
    'GeneratorBase', 'GeneratorError', 'GeneratorMethods', 'Generic', 'GenericObject', 'GenericServer',
    'Get', 'GetoptLong', 'GhostMethod', 'Git', 'GitSet', 'GitSpecification', 'Glob', 'Group', 'Guid', 'GuidBase',
    'GzipFile', 'GzipReader', 'GzipWriter', 'HINFO', 'HMAC', 'HMACError', 'HTMLUtils', 'HTTP', 'HTTPAccepted',
    'HTTPAlreadyReported', 'HTTPAuth', 'HTTPBadGateway', 'HTTPBadRequest', 'HTTPBadResponse', 'HTTPClientError',
    'HTTPClientException', 'HTTPConflict', 'HTTPContinue', 'HTTPCreated', 'HTTPEarlyHints', 'HTTPError',
    'HTTPExceptions', 'HTTPExpectationFailed', 'HTTPFailedDependency', 'HTTPFatalError', 'HTTPForbidden',
    'HTTPFound', 'HTTPGatewayTimeOut', 'HTTPGatewayTimeout', 'HTTPGenericRequest', 'HTTPGone',
    'HTTPHeader', 'HTTPHeaderSyntaxError', 'HTTPIMUsed', 'HTTPInformation', 'HTTPInsufficientStorage',
    'HTTPInternalServerError', 'HTTPLengthRequired', 'HTTPLocked', 'HTTPLoopDetected', 'HTTPMethodNotAllowed',
    'HTTPMisdirectedRequest', 'HTTPMovedPermanently', 'HTTPMovedTemporarily', 'HTTPMultiStatus',
    'HTTPMultipleChoice', 'HTTPMultipleChoices', 'HTTPNetworkAuthenticationRequired', 'HTTPNoContent',
    'HTTPNonAuthoritativeInformation', 'HTTPNotAcceptable', 'HTTPNotExtended', 'HTTPNotFound',
    'HTTPNotImplemented', 'HTTPNotModified', 'HTTPOK', 'HTTPPartialContent', 'HTTPPayloadTooLarge',
    'HTTPPaymentRequired', 'HTTPPermanentRedirect', 'HTTPPreconditionFailed', 'HTTPPreconditionRequired',
    'HTTPProcessing', 'HTTPProxyAuthenticationRequired', 'HTTPProxyServer', 'HTTPRangeNotSatisfiable',
    'HTTPRedirect', 'HTTPRedirection', 'HTTPRequest', 'HTTPRequestEntityTooLarge', 'HTTPRequestHeaderFieldsTooLarge',
    'HTTPRequestTimeOut', 'HTTPRequestTimeout', 'HTTPRequestURITooLarge', 'HTTPRequestURITooLong',
    'HTTPRequestedRangeNotSatisfiable', 'HTTPResetContent', 'HTTPResponse', 'HTTPRetriableError',
    'HTTPS', 'HTTPSeeOther', 'HTTPServer', 'HTTPServerError', 'HTTPServerException', 'HTTPServiceUnavailable',
    'HTTPServlet', 'HTTPServletError', 'HTTPStatus', 'HTTPSuccess', 'HTTPSwitchProtocol', 'HTTPTemporaryRedirect',
    'HTTPTooManyRequests', 'HTTPURITooLong', 'HTTPUnauthorized', 'HTTPUnavailableForLegalReasons',
    'HTTPUnknownResponse', 'HTTPUnprocessableEntity', 'HTTPUnsupportedMediaType', 'HTTPUpgradeRequired',
    'HTTPUseProxy', 'HTTPUtils', 'HTTPVariantAlsoNegotiates', 'HTTPVersion', 'HTTPVersionNotSupported',
    'Handle', 'Handler', 'Handlers', 'HardBreak', 'Hash', 'Head', 'Help', 'HelpCommand', 'Hosts', 'Hour', 'HourBase',
    'Htdigest', 'Htgroup', 'HtmlExtension', 'Htpasswd', 'I', 'IMAP', 'IN', 'IO', 'IOSource', 'IPAddr', 'IPSocket',
    'IRB', 'ITunesBaseModel', 'ITunesCategories', 'ITunesCategoriesBase', 'ITunesCategory', 'ITunesCategoryBase',
    'ITunesChannelModel', 'ITunesDuration', 'ITunesDurationBase', 'ITunesImage', 'ITunesImageBase',
    'ITunesItemModel', 'ITunesModelUtils', 'ITunesOwner', 'ITunesOwnerBase', 'Icon', 'IconBase', 'Id',
    'Ifaddr', 'Image', 'ImageBase', 'ImageFavicon', 'ImageFaviconBase', 'ImageFaviconModel', 'ImageItem',
    'ImageItemBase', 'ImageItemModel', 'ImageModelUtils', 'Importer', 'ImpossibleDependenciesError',
    'Include', 'IndentedParagraph', 'IndexSet', 'IndexSpecification', 'Indexer', 'Inflate', 'Info', 'InfoCommand',
    'InheritedReader', 'Inline', 'InlineParser', 'InnerStateLex', 'InputEOFError', 'InputMethod',
    'InputsScanner', 'Inspector', 'InstallCommand', 'InstallError', 'InstallUpdateOptions', 'Installed',
    'InstalledSpecification', 'Installer', 'InstallerSet', 'InstallerTestCase', 'Instance', 'Instruction',
    'Integer', 'Interleave', 'InternalObjectWrapper', 'InvalidAddressError', 'InvalidArgument',
    'InvalidComponentError', 'InvalidEncoding', 'InvalidHashTupleKey', 'InvalidHeader', 'InvalidIndexError',
    'InvalidOption', 'InvalidPrefixError', 'InvalidRSSError', 'InvalidSpecificationException',
    'InvalidURIError', 'Irb', 'IrbCommand', 'IrbLoader', 'Item', 'ItemBase', 'Items', 'ItemsBase', 'JRuby',
    'JSON', 'JSONError', 'JSONTree', 'Jacobian', 'JobManager', 'Jobs', 'JsonIndex', 'KDF', 'KDFError', 'Kconv',
    'Kernel', 'Kill', 'LDAP', 'LDAPS', 'LOC', 'LOG_MASK', 'LOG_UPTO', 'LUPDecomposition', 'LUSolve', 'LengthError',
    'Level', 'LeveledNotifier', 'Li', 'Licenses', 'Light', 'LightParser', 'Link', 'LinkBase', 'Links', 'LinksBase',
    'List', 'ListCommand', 'ListItem', 'ListenerMixin', 'Literals', 'Load', 'LoadAbort', 'LoadError', 'Local',
    'LocalRemoteOptions', 'LocalSpecification', 'Locale', 'Lock', 'LockCommand', 'LockModeFailer',
    'LockSet', 'LockSpecification', 'Lockfile', 'Log', 'LogDevice', 'Logger', 'Logging', 'LoginAuthenticator',
    'Logo', 'LogoBase', 'LowMethods', 'MDNS', 'MINFO', 'MLSxEntry', 'MX', 'Macros', 'MailTo', 'MakeDirs', 'MakeMakefile',
    'Maker', 'MalformedCSVError', 'Mapping', 'Mark', 'Markdown', 'Markup', 'MatchP', 'Matrix', 'MemError',
    'MemoEntry', 'MemoryStore', 'MessageExtractor', 'Meta', 'MetaMethod', 'MethodAttr', 'MethodExtender',
    'MirrorCommand', 'MissingArgument', 'MissingAttributeError', 'MissingFileError', 'MissingSpecError',
    'MissingSpecVersionError', 'MissingTagError', 'MissingUnicodeSupport', 'Mixin', 'Mkcol', 'MockGemUi',
    'Molinillo', 'Monitor', 'MonitorMixin', 'Move', 'NKF', 'NS', 'NSError', 'NXDomain', 'Name', 'NameError', 'NameTuple',
    'Namespace', 'NeedDict', 'NeedlessArgument', 'NestingError', 'Net', 'Netscape', 'Newton', 'NilClass',
    'NoAliasRuby', 'NoAliasYAMLTree', 'NoArgument', 'NoFooter', 'NoMsgNotifier', 'NoResponseError',
    'NoSuchDependencyError', 'NoWrite', 'Node', 'Nodes', 'NonSeekableIO', 'Nop', 'Normal', 'NormalClass',
    'NormalModule', 'NotAvailableValueError', 'NotExpectedTagError', 'NotFoundError', 'NotSetError',
    'NotValidXMLParser', 'NotWellFormedError', 'NotationDecl', 'Notifier', 'NotifyTemplateEntry',
    'NullSocket', 'NullStore', 'NumValidator', 'OCSP', 'OCSPError', 'OLEProperty', 'Object', 'ObjectId',
    'ObjectSpace', 'Observable', 'Old', 'Omap', 'OneOrMore', 'OpenCommand', 'OpenRead', 'OpenSSL', 'OpenSSLError',
    'OpenStruct', 'OpenURI', 'OperationNotSupportedError', 'Option', 'OptionMap', 'OptionParser',
    'Optional', 'OptionalArgument', 'Options', 'OtherResolvError', 'OutdatedCommand', 'Output', 'OutputMethod',
    'OverlappedPrefixError', 'OwnerCommand', 'PATTERN', 'PI', 'PKey', 'PKeyError', 'PO', 'POEntry', 'POPAuthenticationError',
    'POPBadResponse', 'POPError', 'POPMail', 'POT', 'PStore', 'PTR', 'PTY', 'Package', 'PackageTask', 'Paragraph',
    'Parent', 'ParseError', 'ParseException', 'Parser', 'ParserError', 'Parsers', 'Patch', 'PathError',
    'PathSupport', 'Pathname', 'Paths', 'Period', 'PermaLink?', 'PersonConstruct', 'PlacedArgument',
    'PlainAuthenticator', 'Platform', 'PlatformMismatch', 'Point', 'Pointer', 'Policy', 'PopWorkspace',
    'PossibilityState', 'Post', 'PreProcess', 'Pretty', 'PrettyPrint', 'Prime', 'Primitive', 'PristineCommand',
    'ProcHandler', 'ProcessController', 'Propfind', 'Proppatch', 'Proxy', 'ProxyAuthenticator', 'ProxyBasicAuth',
    'ProxyDigestAuth', 'PseudoPrimeGenerator', 'Psych', 'Published', 'PullEvent', 'PullParser', 'PushCommand',
    'PushWorkspace', 'Put', 'Query', 'QueryCommand', 'QueryExtension', 'QuickPath', 'Quiet', 'RD', 'RDF', 'RDoc',
    'RDocTask', 'REGEXP', 'REXML', 'REXMLLikeXMLParser', 'REXMLListener', 'REXMLParser', 'RI', 'RSA', 'RSAError',
    'RSS', 'RSSBase', 'Racc', 'Raise', 'Rake', 'RakeBuilder', 'Random', 'RandomError', 'Range', 'Rational', 'Raw',
    'RbConfig', 'RdocCommand', 'Readline', 'ReadlineInputMethod', 'RecipientInfo', 'Recorder', 'Redirect',
    'Ref', 'RefError', 'Regexp', 'RegexpHandling', 'RelaxNG', 'RemoteError', 'RemoteFetcher', 'RemoteInstallationCancelled',
    'RemoteInstallationSkipped', 'RemoteSourceException', 'Request', 'RequestCanceledError',
    'RequestError', 'RequestExpiredError', 'RequestSet', 'Requester', 'Require', 'RequiredArgument',
    'Requirement', 'RequirementList', 'Resolution', 'ResolutionState', 'Resolv', 'ResolvError', 'ResolvTimeout',
    'Resolver', 'ResolverError', 'Resource', 'Response', 'ResponseError', 'ResponseParseError', 'Restricted',
    'RestrictedStream', 'Revoked', 'RevokedError', 'Rights', 'RightsBase', 'Rinda', 'RindaError', 'RingFinger',
    'RingProvider', 'RingServer', 'Ripper', 'RipperStateLex', 'RootElementMixin', 'Row', 'Rss', 'Ruby',
    'RubyLex', 'RubyToken', 'RubyTools', 'RubyVM', 'RubyVersionMismatch', 'RubygemsHook', 'Rule', 'RuleInfo',
    'RuntimeRequirementNotMetError', 'SDBM', 'SDBMError', 'SJISHandler', 'SLex', 'SMTP', 'SMTPAuthenticationError',
    'SMTPError', 'SMTPFatalError', 'SMTPServerBusy', 'SMTPSyntaxError', 'SMTPUnknownError', 'SMTPUnsupportedCommand',
    'SNIRequest', 'SOA', 'SOCKSSocket', 'SP', 'SPKI', 'SPKIError', 'SP_Z', 'SRV', 'SSL', 'SSLConfig', 'SSLContext',
    'SSLError', 'SSLErrorWaitReadable', 'SSLErrorWaitWritable', 'SSLServer', 'SSLSocket', 'SafeYAML',
    'Scalar', 'ScalarScanner', 'Scanf', 'Scanner', 'SearchCommand', 'Section', 'SecureRandom', 'Security',
    'SecurityOption', 'Seq', 'Sequence', 'Server', 'ServerCommand', 'ServerError', 'Servlet', 'Session',
    'SessionError', 'Set', 'SetupCommand', 'SetupDefaultDate', 'SetupDefaultLanguage', 'SetupMaker',
    'Severity', 'Shell', 'Shellwords', 'Signer', 'SignerInfo', 'SigninCommand', 'SignoutCommand', 'SilentDownloadReporter',
    'SilentProgressReporter', 'SilentUI', 'Simple', 'SimpleDelegator', 'SimpleProgressReporter',
    'SimpleRenewer', 'SimpleServer', 'SingleClass', 'SingleForwardable', 'SingleLine', 'SingleResponse',
    'Singleton', 'Size', 'SkipDays', 'SkipDaysBase', 'SkipHours', 'SkipHoursBase', 'SlashModel', 'Socket',
    'SocketError', 'SocketForwarder', 'SortedSet', 'Source', 'SourceBase', 'SourceFactory', 'SourceFetchProblem',
    'SourceList', 'SourceSet', 'SourcesCommand', 'SpecFetcher', 'SpecFetcherSetup', 'SpecSpecification',
    'SpecificFile', 'SpecificGemNotFoundException', 'Specification', 'SpecificationCommand',
    'SpecificationPolicy', 'SpecificationProvider', 'StaleCommand', 'State', 'StaticSet', 'Stats',
    'Status', 'StdioInputMethod', 'StdioOutputMethod', 'Store', 'StoreContext', 'StoreError', 'Stream',
    'StreamEnd', 'StreamError', 'StreamListener', 'StreamParser', 'StreamUI', 'Streaming', 'String',
    'StringIO', 'StringInputMethod', 'StringScanner', 'Struct', 'StubSpecification', 'Subtitle', 'SubtitleBase',
    'Success', 'Summary', 'Switch', 'Syck', 'Symbol', 'SyncEnumerator', 'Synchronizer', 'SyndicationModel',
    'SyntaxError', 'Syslog', 'SystemCommand', 'SystemExitException', 'TCPServer', 'TCPSocket', 'TSort',
    'TTY', 'TXT', 'Table', 'Tag', 'TarHeader', 'TarInvalidError', 'TarReader', 'TarTestCase', 'TarWriter',
    'Task', 'TaxonomyTopic', 'TaxonomyTopicBase', 'TaxonomyTopicModel', 'TaxonomyTopics', 'TaxonomyTopicsBase',
    'TaxonomyTopicsModel', 'Tee', 'TempIO', 'Tempfile', 'Template', 'TemplateEntry', 'TermError', 'TestCase',
    'Text', 'TextConstruct', 'TextFormatterTestCase', 'TextInput', 'Textinput', 'TextinputBase', 'ThWait',
    'Thread', 'ThreadedDownloadReporter', 'Time', 'Timeout', 'TimeoutError', 'TimeoutHandler', 'TimerIdConv',
    'Title', 'TitleBase', 'TkError', 'TkId', 'TkNode', 'TkOPASGN', 'TkOp', 'TkUnknownChar', 'TkVal', 'Tms', 'ToAnsi',
    'ToBs', 'ToHtml', 'ToHtmlCrossref', 'ToHtmlSnippet', 'ToJoinedParagraph', 'ToLabel', 'ToMarkdown',
    'ToRdoc', 'ToRuby', 'ToTableOfContents', 'ToTest', 'ToTtOnly', 'Token', 'TokenStream', 'Tokenizer',
    'TomDoc', 'TooLongFileName', 'TooMuchTagError', 'TopLevel', 'Trace', 'Tracer', 'TrackBackAbout',
    'TrackBackAboutBase', 'TrackBackAboutsBase', 'TrackBackModel', 'TrackBackPing', 'TrackBackUtils',
    'Transitive', 'TreeBuilder', 'TreeParser', 'TrialDivision', 'TrialDivisionGenerator', 'TrueClass',
    'TrustDir', 'Tuple', 'TupleBag', 'TupleBin', 'TupleEntry', 'TupleSpace', 'TupleSpaceProxy', 'UDPSocket',
    'UDPSource', 'UI', 'UNIXServer', 'UNIXSocket', 'URI', 'URIContentModel', 'UltraLightParser', 'UndefinedNamespaceException',
    'UnexpectedEOF', 'UninstallCommand', 'UninstallError', 'Uninstaller', 'UnknownConversionMethodError',
    'UnknownHostError', 'UnknownLocker', 'UnknownTagError', 'Unlock', 'UnoptimizedStringIO', 'UnpackCommand',
    'UnsatisfiableDependencyError', 'UnsupportedMakerVersionError', 'UpdateCommand', 'Updated',
    'Uri', 'UriFormatter', 'UserDB', 'UserInteraction', 'Util', 'Utils', 'VARIANT', 'Validation', 'ValidationException',
    'Validator', 'Vector', 'Vendor', 'VendorSet', 'VendorSpecification', 'Verbatim', 'Verbose', 'VerboseProgressReporter',
    'VerificationError', 'Version', 'VersionConflict', 'VersionError', 'VersionOption', 'Vertex',
    'Visitor', 'Visitors', 'Void', 'WEBrick', 'WKS', 'WaitReadable', 'WaitTemplateEntry', 'WaitWritable',
    'WeakRef', 'WhichCommand', 'WorkSpace', 'Workspaces', 'Writer', 'XML', 'XMLDecl', 'XMLParserListener',
    'XMLParserNotFound', 'XMLParserParser', 'XMLScanListener', 'XMLScanParser', 'XMLStyleSheet',
    'XMLStyleSheetMixin', 'XMLStyleSheets', 'XMLTokens', 'XMP', 'XPath', 'XPathNode', 'XPathParser',
    'YAML', 'YAMLTree', 'YankCommand', 'YesOther', 'Z', 'ZStream', 'ZeroOrMore', 'ZeroVectorError', 'Zlib'
]
# ------------------------------- KEYWORD -------------------------------------------------------------------------

class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name = 'deoplete-ruby-stdlib'
        self.filetypes = ['ruby']
        self.mark = '[ruby-stdlib]'
        self.rank = 5 

    def get_complete_position(self, context):
        m = re.search('[a-zA-Z0-9_?!]*$', context['input'])
        return m.start() if m else -1

    def gather_candidates(self, context):
        try:
            dic = ruby_stdlib_keywords
            return dic
        except Exception:
            traceback.print_exc()
